# Generated by Django 2.1.7 on 2019-03-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
