# Generated by Django 2.1.7 on 2019-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
